# Setup
title:               "MIA: Music Interpretation Analysis"
# tagline:             'MIA'
description:         'The Home for Music Information Processing applications about Music Interpretation Analysis'
url:                 'https://limunimi.github.io/'
baseurl:             'MIA-Music-Interpretation-Analysis/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Federico Simonetta
  url:               https://federicosimonetta.eu.org

# Gems
plugins:
  - jekyll-paginate
